# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcf9d146197701f8e9a85abb5c6d34446ca268c852d88f323fc2100feea3d8d93253448e352c58187bc10f6c98d02fb98a5f45aced983c3de2038433aaae82d6

test:
  secret_key_base: 7bc3c61f132ee294a9a934560f399249c3043236795b82fdb6ee45b4804463b327bde40bfbcb0127b1dca9224176b7784503a91cf7b7f5503c79dcc41897870a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
